import streamlit as st
import pandas as pd

# --- Conjunto de Datos de Búsquedas y Temas de Interés ---
# Este es nuestro "historial" de búsquedas y los temas de interés asociados.
# En un sistema real, esto provendría de una base de datos o un data lake.
data = {
    "busqueda": [
        "coches electricos",
        "bicicletas de montaña",
        "peliculas de ciencia ficcion",
        "suplementos fitness",
        "pantallas LED decorativas",
        "accesorios para mascotas",
        "aplicaciones de recetas",
        "auriculares inalambricos gym",
        "cargador solar portátil",
        "coches electricos",
        "mochilas de senderismo",
        "juegos de estrategia",
        "ropa termica para correr",
        "luces inteligentes",
        "alimento premium gatos",
        "yoga principiantes",
        "pantalla 4K",
        "cargador solar portátil",
        "coches electricos",
        "bicicletas de montaña",
        "libros de misterio",
        "entrenamiento en casa",
        "luces inteligentes",
        "accesorios para mascotas",
        "tupper saludables",
        "reloj Garmin",
        "viajes a la playa",
        "motos deportivas",
        "mochilas de senderismo",
        "juegos de estrategia",
        "calcetines deportivos",
        "escritorios ajustables",
        "accesorios para mascotas",
        "yoga principiantes",
        "drone para fotografia",
        "cargador solar portátil",
        "coches electricos",
        "mochilas de senderismo",
        "libros de misterio",
        "ropa de ejercicio",
        "decoracion de interiores",
        "accesorios para mascotas",
        "yoga principiantes",
        "camara deportiva",
        "hoteles baratos",
        "coches electricos",
        "bicicletas de montaña",
        "peliculas romanticas",
        "calcetines deportivos",
        "macetas decorativas",
        "accesorios para mascotas",
        "aplicaciones de recetas",
        "consolas de nueva generacion",
        "hoteles baratos",
        "coches electricos",
        "mochilas de senderismo",
        "libros de misterio",
        "zapatillas deportivas",
        "escritorios ajustables",
        "accesorios para mascotas",
        "colchoneta yoga",
        "camara deportiva",
        "viajes a la playa",
        "coches electricos",
        "mochilas de senderismo",
        "libros de misterio",
        "bicicleta estatica",
        "macetas decorativas",
        "accesorios para mascotas",
        "recetas veganas",
        "drone para fotografia",
        "power bank para viajes",
        "coches electricos",
        "bicicletas de montaña",
        "series policiacas",
        "camisetas running",
        "robots de limpieza",
        "alimento premium gatos",
        "documentales sobre salud",
        "mouse gamer",
        "cargador solar portátil",
        "motos deportivas",
        "mochilas de senderismo",
        "juegos de estrategia",
        "ropa termica para correr",
        "sillas ergonomicas",
        "accesorios para mascotas",
        "recetas veganas",
        "mouse gamer",
        "hoteles baratos",
        "coches electricos",
        "bicicletas de montaña",
        "peliculas de ciencia ficcion",
        "calcetines deportivos",
        "robots de limpieza",
        "correas para perros",
        "yoga principiantes",
        "drone para fotografia",
        "cargador solar portátil",
        "motos deportivas",
        "zapatos de senderismo",
        "peliculas de accion",
        "ropa de ejercicio",
        "luces inteligentes",
        "correas para perros",
        "yoga principiantes",
        "drone para fotografia",
        "power bank para viajes",
        "coches electricos",
        "bicicletas de montaña",
        "peliculas de accion",
        "ropa de ejercicio",
        "luces inteligentes",
        "alimento premium gatos",
        "recetas veganas",
        "mouse gamer",
        "hoteles baratos",
        "motos deportivas",
        "zapatos de senderismo",
        "libros de misterio",
        "calcetines deportivos",
        "sillas ergonomicas",
        "accesorios para mascotas",
        "tupper saludables",
        "teclado mecanico",
        "viajes a la playa",
        "coches electricos",
        "bicicletas de montaña",
        "peliculas de ciencia ficcion",
        "bicicleta estatica",
        "macetas decorativas",
        "correas para perros",
        "colchoneta yoga",
        "drone para fotografia",
        "hoteles baratos",
        "coches electricos",
        "bicicletas de montaña",
        "peliculas de accion",
        "entrenamiento en casa",
        "robots de limpieza",
        "accesorios para mascotas",
        "tupper saludables",
        "pantalla 4K",
        "viajes a la playa",
        "motos deportivas",
        "zapatos de senderismo",
        "series de fantasia",
        "suplementos fitness",
        "herramientas de jardin",
        "accesorios para mascotas"
    ],
    "tema_interes": [
        "automovilismo",
        "deportes al aire libre",
        "entretenimiento",
        "fitness",
        "hogar y jardin",
        "mascotas",
        "salud y bienestar",
        "tecnologia",
        "viajes",
        "automovilismo",
        "deportes al aire libre",
        "entretenimiento",
        "fitness",
        "hogar y jardin",
        "mascotas",
        "salud y bienestar",
        "tecnologia",
        "viajes",
        "automovilismo",
        "deportes al aire libre",
        "entretenimiento",
        "fitness",
        "hogar y jardin",
        "mascotas",
        "salud y bienestar",
        "tecnologia",
        "viajes",
        "automovilismo",
        "deportes al aire libre",
        "entretenimiento",
        "fitness",
        "hogar y jardin",
        "mascotas",
        "salud y bienestar",
        "tecnologia",
        "viajes",
        "automovilismo",
        "deportes al aire libre",
        "entretenimiento",
        "fitness",
        "hogar y jardin",
        "mascotas",
        "salud y bienestar",
        "tecnologia",
        "viajes",
        "automovilismo",
        "deportes al aire libre",
        "entretenimiento",
        "fitness",
        "hogar y jardin",
        "mascotas",
        "salud y bienestar",
        "tecnologia",
        "viajes",
        "automovilismo",
        "deportes al aire libre",
        "entretenimiento",
        "fitness",
        "hogar y jardin",
        "mascotas",
        "salud y bienestar",
        "tecnologia",
        "viajes",
        "automovilismo",
        "deportes al aire libre",
        "entretenimiento",
        "fitness",
        "hogar y jardin",
        "mascotas",
        "salud y bienestar",
        "tecnologia",
        "viajes",
        "automovilismo",
        "deportes al aire libre",
        "entretenimiento",
        "fitness",
        "hogar y jardin",
        "mascotas",
        "salud y bienestar",
        "tecnologia",
        "viajes",
        "automovilismo",
        "deportes al aire libre",
        "entretenimiento",
        "fitness",
        "hogar y jardin",
        "mascotas",
        "salud y bienestar",
        "tecnologia",
        "viajes",
        "automovilismo",
        "deportes al aire libre",
        "entretenimiento",
        "fitness",
        "hogar y jardin",
        "mascotas",
        "salud y bienestar",
        "tecnologia",
        "viajes",
        "automovilismo",
        "deportes al aire libre",
        "entretenimiento",
        "fitness",
        "hogar y jardin",
        "mascotas",
        "salud y bienestar",
        "tecnologia",
        "viajes",
        "automovilismo",
        "deportes al aire libre",
        "entretenimiento",
        "fitness",
        "hogar y jardin",
        "mascotas",
        "salud y bienestar",
        "tecnologia",
        "viajes",
        "automovilismo",
        "deportes al aire libre",
        "entretenimiento",
        "fitness",
        "hogar y jardin",
        "mascotas"
    ],
    "anuncio_sugerido": [
        "Test drive de Tesla",
        "Bicicletas de montaña Trek",
        "Clásicos del cine romántico",
        "Descuento en ropa Adidas",
        "Macetas de diseño",
        "Comida Royal Canin gatos",
        "Recetario vegano gratuito",
        "Pantalla LG 4K de 32 pulgadas",
        "Hoteles con descuento en Punta Cana",
        "Test drive de Tesla",
        "Botas Columbia para senderismo",
        "Películas de acción recomendadas",
        "Descuento en ropa Adidas",
        "Macetas de diseño",
        "Juguetes y accesorios para gatos",
        "Tuppers herméticos y saludables",
        "Mouse gamer RGB",
        "Paquetes turísticos a Cancún",
        "Test drive de Tesla",
        "Mochilas The North Face",
        "Maratón de series policiacas",
        "App de entrenamiento personalizado",
        "Roomba con sensor inteligente",
        "Comida Royal Canin gatos",
        "Apps con más de 10,000 recetas",
        "Pantalla LG 4K de 32 pulgadas",
        "Paquetes turísticos a Cancún",
        "Test drive de Tesla",
        "Botas Columbia para senderismo",
        "Novelas de suspense",
        "App de entrenamiento personalizado",
        "Escritorio regulable eléctrico",
        "Juguetes y accesorios para gatos",
        "Recetario vegano gratuito",
        "GoPro Hero en oferta",
        "Power banks con carga rápida",
        "Test drive de Tesla",
        "Bicicletas de montaña Trek",
        "Clásicos del cine romántico",
        "Pack de calcetines Nike",
        "Luces inteligentes Alexa",
        "Comida Royal Canin gatos",
        "Recetario vegano gratuito",
        "Mouse gamer RGB",
        "Paquetes turísticos a Cancún",
        "Test drive de Tesla",
        "Botas Columbia para senderismo",
        "Clásicos del cine romántico",
        "Descuento en ropa Adidas",
        "Luces inteligentes Alexa",
        "Juguetes y accesorios para gatos",
        "App de meditación premium",
        "Drones DJI con cámara 4K",
        "Cargador solar para camping",
        "Test drive de Tesla",
        "Mochilas The North Face",
        "Sagas literarias épicas",
        "Descuento en bicicletas estáticas",
        "Sillas ergonómicas para home office",
        "Correas resistentes para perros grandes",
        "Tuppers herméticos y saludables",
        "Pantalla LG 4K de 32 pulgadas",
        "Paquetes turísticos a Cancún",
        "Motos Ducati a tu medida",
        "Bicicletas de montaña Trek",
        "Películas de acción recomendadas",
        "Oferta de zapatillas Nike",
        "Macetas de diseño",
        "Juguetes y accesorios para gatos",
        "Set de yoga con colchoneta ecológica",
        "Nuevo Apple Watch",
        "Power banks con carga rápida",
        "Motos Ducati a tu medida",
        "Bicicletas de montaña Trek",
        "Sagas literarias épicas",
        "Descuento en bicicletas estáticas",
        "Roomba con sensor inteligente",
        "Comida Royal Canin gatos",
        "Set de yoga con colchoneta ecológica",
        "Nuevo Apple Watch",
        "Power banks con carga rápida",
        "Test drive de Tesla",
        "Bicicletas de montaña Trek",
        "Maratón de series policiacas",
        "Pesas rusas con envío gratis",
        "Escritorio regulable eléctrico",
        "Comida Royal Canin gatos",
        "App de meditación premium",
        "Audífonos Bluetooth JBL",
        "Paquetes turísticos a Cancún",
        "Motos Ducati a tu medida",
        "Bicicletas de montaña Trek",
        "Estrenos en Netflix",
        "Promo en proteínas",
        "Herramientas de jardinería profesionales",
        "Juguetes y accesorios para gatos",
        "Top 10 libros de autoayuda",
        "GoPro Hero en oferta",
        "Power banks con carga rápida",
        "Motos Ducati a tu medida",
        "Bicicletas de montaña Trek",
        "Clásicos del cine romántico",
        "Promo en proteínas",
        "Macetas de diseño",
        "Correas resistentes para perros grandes",
        "Mejores documentales de salud 2024",
        "GoPro Hero en oferta",
        "Power banks con carga rápida",
        "Test drive de Tesla",
        "Mochilas The North Face",
        "Maratón de series policiacas",
        "Ropa deportiva Under Armour",
        "Luces inteligentes Alexa",
        "Comida Royal Canin gatos",
        "Clases de yoga en línea",
        "Ofertas en relojes Garmin",
        "Hoteles con descuento en Punta Cana",
        "Motos Ducati a tu medida",
        "Botas Columbia para senderismo",
        "Sagas literarias épicas",
        "Mancuernas ajustables PowerBlock",
        "Macetas de diseño",
        "Correas resistentes para perros grandes",
        "Top 10 libros de autoayuda",
        "Mouse gamer RGB",
        "Hoteles con descuento en Punta Cana",
        "Test drive de Tesla",
        "Bicicletas de montaña Trek",
        "Clásicos del cine romántico",
        "Promo en proteínas",
        "Plantas exóticas para tu hogar",
        "Juguetes y accesorios para gatos",
        "Recetario vegano gratuito",
        "Pantalla LG 4K de 32 pulgadas",
        "Cargador solar para camping",
        "Test drive de Tesla",
        "Botas Columbia para senderismo",
        "Películas de acción recomendadas",
        "Mancuernas ajustables PowerBlock",
        "Sillas ergonómicas para home office",
        "Comida Royal Canin gatos",
        "Clases de yoga en línea",
        "Pantalla LG 4K de 32 pulgadas",
        "Cargador solar para camping",
        "Motos Ducati a tu medida",
        "Mochilas The North Face",
        "Juegos para PlayStation 5",
        "2x1 en batidos de proteína vegana",
        "Decoración estilo escandinavo",
        "Comida Royal Canin gatos"
    ]
}

df_busquedas = pd.DataFrame(data)

# --- Función para Sugerir Anuncios ---
def sugerir_anuncios(busqueda_usuario):
    # Convertir la búsqueda del usuario a minúsculas para una comparación insensible a mayúsculas
    busqueda_usuario_lower = busqueda_usuario.lower()

    # Buscar temas de interés relacionados con la búsqueda del usuario
    temas_relacionados = df_busquedas[df_busquedas["busqueda"].str.contains(busqueda_usuario_lower, case=False)]["tema_interes"].unique()

    sugerencias = []
    if len(temas_relacionados) > 0:
        # Si encontramos temas relacionados, sugerimos anuncios basados en esos temas
        for tema in temas_relacionados:
            anuncios_posibles = df_busquedas[df_busquedas["tema_interes"] == tema]["anuncio_sugerido"].tolist()
            sugerencias.extend(anuncios_posibles)
    else:
        # Si no hay coincidencias directas, se podría implementar una lógica más compleja
        # (por ejemplo, buscar palabras clave, usar modelos de embeddings, etc.)
        # Para este ejemplo simple, si no hay coincidencia directa, sugerimos anuncios generales
        sugerencias = ["Anuncios generales: ¡Descubre ofertas en productos variados!", "Prueba nuestros servicios premium", "Explora nuevas categorías"]

    # Eliminar duplicados y devolver una muestra limitada
    return list(set(sugerencias))[:5] # Limitar a 5 sugerencias para no abrumar

# --- Interfaz de Usuario con Streamlit ---
st.set_page_config(page_title="Emulación de Anuncios Sugeridos", layout="centered")

st.title("🔎 Emulación de Sugerencia de Anuncios Basada en Búsquedas")
st.markdown("""
Este ejemplo simula cómo las búsquedas de un usuario en una plataforma
podrían influir en los anuncios que se le muestran.
Introduce algunas palabras clave en el buscador y mira qué anuncios se sugieren.
""")

st.subheader("Simulador de Búsqueda")
user_input = st.text_input("¿Qué estás buscando hoy?", placeholder="Ej: zapatillas deportivas, peliculas de ciencia ficcion, viajes")

if user_input:
    st.subheader("Anuncios Sugeridos para ti:")
    sugerencias_anuncios = sugerir_anuncios(user_input)

    if sugerencias_anuncios:
        for anuncio in sugerencias_anuncios:
            st.info(f"👉 {anuncio}")
    else:
        st.write("No hay sugerencias de anuncios en este momento para tu búsqueda específica. ¡Intenta con otras palabras clave!")

st.markdown("---")
st.subheader("Cómo funciona (Detrás de Escena):")
st.markdown("""
1.  **Conjunto de Datos:** Tenemos un conjunto de datos simple que asocia palabras clave de búsqueda con "temas de interés" (por ejemplo, 'fitness', 'entretenimiento', 'viajes').
2.  **Mapeo:** Cuando ingresas una búsqueda, el sistema intenta mapear tus palabras clave a uno o más de estos temas de interés.
3.  **Sugerencia:** Una vez que se identifica un tema de interés, se muestran anuncios que están pre-asociados con ese tema en nuestro conjunto de datos.
""")

st.subheader("Datos de Ejemplo Utilizados:")
st.dataframe(df_busquedas)

st.caption("Nota: Este es un ejemplo simplificado. Un sistema de sugerencia de anuncios real sería mucho más complejo, utilizando algoritmos de machine learning, análisis de comportamiento del usuario, historial de clics, datos demográficos, etc.")
