import streamlit as st
import pandas as pd

# --- Conjunto de Datos de Búsquedas y Temas de Interés ---
# Este es nuestro "historial" de búsquedas y los temas de interés asociados.
# En un sistema real, esto provendría de una base de datos o un data lake.
data = {
    "busqueda": [
        "accesorios para mascotas",
        "bicicletas de montaña",
        "bicicleta estatica",
        "coches electricos",
        "consolas de nueva generacion",
        "documentales sobre salud",
        "juegos de estrategia",
        "decoracion de interiores",
        "hoteles baratos",
        "accesorios para mascotas",
        "mochilas de senderismo",
        "batidos de proteina",
        "motos deportivas",
        "drone para fotografia",
        "libros de autoayuda",
        "peliculas de accion",
        "herramientas de jardin",
        "power bank para viajes",
        "alimento premium gatos",
        "zapatos de senderismo",
        "suplementos fitness",
        "coches electricos",
        "mouse gamer",
        "recetas veganas",
        "libros de misterio",
        "sillas ergonomicas",
        "hoteles baratos",
        "correas para perros",
        "bicicletas de montaña",
        "zapatillas deportivas",
        "motos deportivas",
        "smartwatch deportivo",
        "yoga principiantes",
        "peliculas de ciencia ficcion",
        "plantas de interior",
        "cargador solar portátil",
        "accesorios para mascotas",
        "zapatos de senderismo",
        "ropa de ejercicio",
        "coches electricos",
        "teclado mecanico",
        "aplicaciones de recetas",
        "series de fantasia",
        "escritorios ajustables",
        "viajes a la playa",
        "alimento premium gatos",
        "mochilas de senderismo",
        "calcetines deportivos",
        "motos deportivas",
        "auriculares gamer",
        "meditacion guiada",
        "videojuegos de rol",
        "macetas decorativas",
        "cargador solar portátil",
        "correas para perros",
        "bicicletas de montaña",
        "entrenamiento en casa",
        "coches electricos",
        "pantalla 4K",
        "recetas saludables",
        "peliculas romanticas",
        "pantallas LED decorativas",
        "viajes a la playa",
        "alimento premium gatos",
        "zapatos de senderismo",
        "camisetas running",
        "motos deportivas",
        "reloj Garmin",
        "colchoneta yoga",
        "series policiacas",
        "luces inteligentes",
        "hoteles baratos",
        "accesorios para mascotas",
        "mochilas de senderismo",
        "mancuernas ajustables",
        "coches electricos",
        "auriculares inalambricos gym",
        "tupper saludables",
        "peliculas de ciencia ficcion",
        "robots de limpieza",
        "cargador solar portátil",
        "correas para perros",
        "zapatos de senderismo",
        "ropa termica para correr",
        "motos deportivas",
        "camara deportiva",
        "libros de autoayuda",
        "juegos de estrategia",
        "herramientas de jardin",
        "power bank para viajes",
        "accesorios para mascotas",
        "bicicletas de montaña",
        "pesas rusas",
        "coches electricos",
        "smartwatch deportivo",
        "documentales sobre salud",
        "series de fantasia",
        "decoracion de interiores",
        "hoteles baratos",
        "alimento premium gatos",
        "mochilas de senderismo",
        "zapatillas deportivas",
        "motos deportivas",
        "consolas de nueva generacion",
        "recetas saludables",
        "peliculas de accion",
        "plantas de interior",
        "viajes a la playa",
        "correas para perros",
        "zapatos de senderismo",
        "ropa de ejercicio",
        "coches electricos",
        "mouse gamer",
        "yoga principiantes",
        "libros de misterio",
        "sillas ergonomicas",
        "hoteles baratos",
        "accesorios para mascotas",
        "bicicletas de montaña",
        "suplementos fitness",
        "motos deportivas",
        "teclado mecanico",
        "aplicaciones de recetas",
        "videojuegos de rol",
        "escritorios ajustables",
        "cargador solar portátil",
        "alimento premium gatos",
        "mochilas de senderismo",
        "bicicleta estatica",
        "coches electricos",
        "auriculares gamer",
        "meditacion guiada",
        "peliculas romanticas",
        "macetas decorativas",
        "power bank para viajes",
        "correas para perros",
        "zapatos de senderismo",
        "camisetas running",
        "motos deportivas",
        "reloj Garmin",
        "colchoneta yoga",
        "series policiacas",
        "pantallas LED decorativas",
        "viajes a la playa",
        "accesorios para mascotas",
        "bicicletas de montaña",
        "entrenamiento en casa",
        "motos deportivas",
        "pantalla 4K",
        "recetas veganas",
        "peliculas de ciencia ficcion",
        "luces inteligentes",
        "hoteles baratos",
        "alimento premium gatos",
        "zapatos de senderismo",
        "batidos de proteina",
        "coches electricos",
        "auriculares inalambricos gym",
        "tupper saludables",
        "juegos de estrategia",
        "robots de limpieza"
    ],
    "tema_interes": [
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin",
        "viajes",
        "mascotas",
        "deportes al aire libre",
        "fitness",
        "automovilismo",
        "tecnologia",
        "salud y bienestar",
        "entretenimiento",
        "hogar y jardin"
    ],
    "anuncio_sugerido": [
        "Correas resistentes para perros grandes",
        "Bicicletas de montaña Trek",
        "Descuento en bicicletas estáticas",
        "Test drive de Tesla",
        "Ofertas en consolas Xbox",
        "Recetario vegano gratuito",
        "Juegos para PlayStation 5",
        "Tiras LED con control remoto",
        "Hoteles con descuento en Punta Cana",
        "Juguetes y accesorios para gatos",
        "Botas Columbia para senderismo",
        "2x1 en batidos de proteína vegana",
        "Test drive de Tesla",
        "Drones DJI con cámara 4K",
        "Top 10 libros de autoayuda",
        "Clásicos del cine romántico",
        "Plantas exóticas para tu hogar",
        "Power banks con carga rápida",
        "Comida Royal Canin gatos",
        "Mochilas The North Face",
        "Promo en proteínas",
        "Motos Ducati a tu medida",
        "Auriculares Razer Kraken",
        "Apps con más de 10,000 recetas",
        "Sagas literarias épicas",
        "Sillas ergonómicas para home office",
        "Paquetes turísticos a Cancún",
        "Juguetes y accesorios para gatos",
        "Botas Columbia para senderismo",
        "Oferta de zapatillas Nike",
        "Motos Ducati a tu medida",
        "Ofertas en relojes Garmin",
        "App de meditación premium",
        "Maratón de series policiacas",
        "Decoración estilo escandinavo",
        "Power banks con carga rápida",
        "Correas resistentes para perros grandes",
        "Botas Columbia para senderismo",
        "Descuento en ropa Adidas",
        "Test drive de Tesla",
        "Teclado mecánico Logitech",
        "Curso de cocina saludable online",
        "Novelas de suspense",
        "Escritorio regulable eléctrico",
        "Cargador solar para camping",
        "Comida Royal Canin gatos",
        "Mochilas The North Face",
        "Pack de calcetines Nike",
        "Test drive de Tesla",
        "Auriculares Razer Kraken",
        "Set de yoga con colchoneta ecológica",
        "Juegos para PlayStation 5",
        "Herramientas de jardinería profesionales",
        "Hoteles con descuento en Punta Cana",
        "Juguetes y accesorios para gatos",
        "Bicicletas de montaña Trek",
        "App de entrenamiento personalizado",
        "Motos Ducati a tu medida",
        "Pantalla LG 4K de 32 pulgadas",
        "Curso de cocina saludable online",
        "Películas de acción recomendadas",
        "Tiras LED con control remoto",
        "Paquetes turísticos a Cancún",
        "Juguetes y accesorios para gatos",
        "Mochilas The North Face",
        "Ropa deportiva Under Armour",
        "Motos Ducati a tu medida",
        "Nuevo Apple Watch",
        "Clases de yoga en línea",
        "Estrenos en Netflix",
        "Luces inteligentes Alexa",
        "Paquetes turísticos a Cancún",
        "Correas resistentes para perros grandes",
        "Botas Columbia para senderismo",
        "Mancuernas ajustables PowerBlock",
        "Test drive de Tesla",
        "Audífonos Bluetooth JBL",
        "Apps con más de 10,000 recetas",
        "Clásicos del cine romántico",
        "Roomba con sensor inteligente",
        "Cargador solar para camping",
        "Juguetes y accesorios para gatos",
        "Mochilas The North Face",
        "Ropa térmica Puma",
        "Motos Ducati a tu medida",
        "GoPro Hero en oferta",
        "Mejores documentales de salud 2024",
        "Steam: descuentos en estrategia",
        "Decoración estilo escandinavo",
        "Power banks con carga rápida",
        "Comida Royal Canin gatos",
        "Bicicletas de montaña Trek",
        "Pesas rusas con envío gratis",
        "Test drive de Tesla",
        "Nuevo Apple Watch",
        "Mejores documentales de salud 2024",
        "Sagas literarias épicas",
        "Plantas exóticas para tu hogar",
        "Hoteles con descuento en Punta Cana",
        "Juguetes y accesorios para gatos",
        "Botas Columbia para senderismo",
        "Oferta de zapatillas Nike",
        "Motos Ducati a tu medida",
        "Ofertas en consolas Xbox",
        "Curso de cocina saludable online",
        "Clásicos del cine romántico",
        "Herramientas de jardinería profesionales",
        "Cargador solar para camping",
        "Correas resistentes para perros grandes",
        "Mochilas The North Face",
        "Descuento en ropa Adidas",
        "Test drive de Tesla",
        "Mouse gamer RGB",
        "App de meditación premium",
        "Novelas de suspense",
        "Sillas ergonómicas para home office",
        "Paquetes turísticos a Cancún",
        "Juguetes y accesorios para gatos",
        "Bicicletas de montaña Trek",
        "Promo en proteínas",
        "Motos Ducati a tu medida",
        "Teclado mecánico Logitech",
        "Apps con más de 10,000 recetas",
        "Juegos para PlayStation 5",
        "Escritorio regulable eléctrico",
        "Hoteles con descuento en Punta Cana",
        "Juguetes y accesorios para gatos",
        "Botas Columbia para senderismo",
        "Descuento en bicicletas estáticas",
        "Test drive de Tesla",
        "Auriculares Razer Kraken",
        "Set de yoga con colchoneta ecológica",
        "Películas de acción recomendadas",
        "Macetas de diseño",
        "Power banks con carga rápida",
        "Correas resistentes para perros grandes",
        "Mochilas The North Face",
        "Ropa deportiva Under Armour",
        "Motos Ducati a tu medida",
        "GoPro Hero en oferta",
        "Clases de yoga en línea",
        "Maratón de series policiacas",
        "Tiras LED con control remoto",
        "Paquetes turísticos a Cancún",
        "Correas resistentes para perros grandes",
        "Botas Columbia para senderismo",
        "App de entrenamiento personalizado",
        "Motos Ducati a tu medida",
        "Pantalla LG 4K de 32 pulgadas",
        "Recetario vegano gratuito",
        "Estrenos en Netflix",
        "Luces inteligentes Alexa"
    ]
}

df_busquedas = pd.DataFrame(data)

# --- Función para Sugerir Anuncios ---
def sugerir_anuncios(busqueda_usuario):
    # Convertir la búsqueda del usuario a minúsculas para una comparación insensible a mayúsculas
    busqueda_usuario_lower = busqueda_usuario.lower()

    # Buscar temas de interés relacionados con la búsqueda del usuario
    temas_relacionados = df_busquedas[df_busquedas["busqueda"].str.contains(busqueda_usuario_lower, case=False)]["tema_interes"].unique()

    sugerencias = []
    if len(temas_relacionados) > 0:
        # Si encontramos temas relacionados, sugerimos anuncios basados en esos temas
        for tema in temas_relacionados:
            anuncios_posibles = df_busquedas[df_busquedas["tema_interes"] == tema]["anuncio_sugerido"].tolist()
            sugerencias.extend(anuncios_posibles)
    else:
        # Si no hay coincidencias directas, se podría implementar una lógica más compleja
        # (por ejemplo, buscar palabras clave, usar modelos de embeddings, etc.)
        # Para este ejemplo simple, si no hay coincidencia directa, sugerimos anuncios generales
        sugerencias = ["Anuncios generales: ¡Descubre ofertas en productos variados!", "Prueba nuestros servicios premium", "Explora nuevas categorías"]

    # Eliminar duplicados y devolver una muestra limitada
    return list(set(sugerencias))[:5] # Limitar a 5 sugerencias para no abrumar

# --- Interfaz de Usuario con Streamlit ---
st.set_page_config(page_title="Emulación de Anuncios Sugeridos", layout="centered")

st.title("🔎 Emulación de Sugerencia de Anuncios Basada en Búsquedas")
st.markdown("""
Este ejemplo simula cómo las búsquedas de un usuario en una plataforma
podrían influir en los anuncios que se le muestran.
Introduce algunas palabras clave en el buscador y mira qué anuncios se sugieren.
""")

st.subheader("Simulador de Búsqueda")
user_input = st.text_input("¿Qué estás buscando hoy?", placeholder="Ej: zapatillas deportivas, peliculas de ciencia ficcion, viajes")

if user_input:
    st.subheader("Anuncios Sugeridos para ti:")
    sugerencias_anuncios = sugerir_anuncios(user_input)

    if sugerencias_anuncios:
        for anuncio in sugerencias_anuncios:
            st.info(f"👉 {anuncio}")
    else:
        st.write("No hay sugerencias de anuncios en este momento para tu búsqueda específica. ¡Intenta con otras palabras clave!")

st.markdown("---")
st.subheader("Cómo funciona (Detrás de Escena):")
st.markdown("""
1.  **Conjunto de Datos:** Tenemos un conjunto de datos simple que asocia palabras clave de búsqueda con "temas de interés" (por ejemplo, 'fitness', 'entretenimiento', 'viajes').
2.  **Mapeo:** Cuando ingresas una búsqueda, el sistema intenta mapear tus palabras clave a uno o más de estos temas de interés.
3.  **Sugerencia:** Una vez que se identifica un tema de interés, se muestran anuncios que están pre-asociados con ese tema en nuestro conjunto de datos.
""")

st.subheader("Datos de Ejemplo Utilizados:")
st.dataframe(df_busquedas)

st.caption("Nota: Este es un ejemplo simplificado. Un sistema de sugerencia de anuncios real sería mucho más complejo, utilizando algoritmos de machine learning, análisis de comportamiento del usuario, historial de clics, datos demográficos, etc.")
