import streamlit as st
import pandas as pd

# --- Conjunto de Datos de Búsquedas y Temas de Interés ---
# Este es nuestro "historial" de búsquedas y los temas de interés asociados.
# En un sistema real, esto provendría de una base de datos o un data lake.
data = {
  "busqueda": [
    "accesorios para mascotas",
    "bicicletas de montaña",
    "bicicleta estatica",
    "coches electricos",
    "consolas de nueva generacion",
    "documentales sobre salud",
    "juegos de estrategia",
    "decoracion de interiores",
    "hoteles baratos",
    "accesorios para mascotas",
    "mochilas de senderismo",
    "batidos de proteina",
    "motos deportivas",
    "drone para fotografia",
    "libros de autoayuda",
    "peliculas de accion",
    "herramientas de jardin",
    "power bank para viajes",
    "alimento premium gatos",
    "zapatos de senderismo",
    "suplementos fitness",
    "coches electricos",
    "mouse gamer",
    "recetas veganas",
    "libros de misterio",
    "sillas ergonomicas",
    "hoteles baratos",
    "correas para perros",
    "bicicletas de montaña",
    "zapatillas deportivas",
    "motos deportivas",
    "smartwatch deportivo",
    "yoga principiantes",
    "peliculas de ciencia ficcion",
    "plantas de interior",
    "cargador solar portátil",
    "accesorios para mascotas",
    "zapatos de senderismo",
    "ropa de ejercicio",
    "coches electricos",
    "teclado mecanico",
    "aplicaciones de recetas",
    "series de fantasia",
    "escritorios ajustables",
    "viajes a la playa",
    "alimento premium gatos",
    "mochilas de senderismo",
    "calcetines deportivos",
    "motos deportivas",
    "auriculares gamer",
    "meditacion guiada",
    "videojuegos de rol",
    "macetas decorativas",
    "cargador solar portátil",
    "correas para perros",
    "bicicletas de montaña",
    "entrenamiento en casa",
    "coches electricos",
    "pantalla 4K",
    "recetas saludables",
    "peliculas romanticas",
    "pantallas LED decorativas",
    "viajes a la playa",
    "alimento premium gatos",
    "zapatos de senderismo",
    "camisetas running",
    "motos deportivas",
    "reloj Garmin",
    "colchoneta yoga",
    "series policiacas",
    "luces inteligentes",
    "hoteles baratos",
    "accesorios para mascotas",
    "mochilas de senderismo",
    "mancuernas ajustables",
    "coches electricos",
    "auriculares inalambricos gym",
    "tupper saludables",
    "peliculas de ciencia ficcion",
    "robots de limpieza",
    "cargador solar portátil",
    "correas para perros",
    "zapatos de senderismo",
    "ropa termica para correr",
    "motos deportivas",
    "camara deportiva",
    "libros de autoayuda",
    "juegos de estrategia",
    "herramientas de jardin",
    "power bank para viajes",
    "accesorios para mascotas",
    "bicicletas de montaña",
    "pesas rusas",
    "coches electricos",
    "smartwatch deportivo",
    "documentales sobre salud",
    "series de fantasia",
    "decoracion de interiores",
    "hoteles baratos",
    "alimento premium gatos",
    "mochilas de senderismo",
    "zapatillas deportivas",
    "motos deportivas",
    "consolas de nueva generacion",
    "recetas saludables",
    "peliculas de accion",
    "plantas de interior",
    "viajes a la playa",
    "correas para perros",
    "zapatos de senderismo",
    "ropa de ejercicio",
    "coches electricos",
    "mouse gamer",
    "yoga principiantes",
    "libros de misterio",
    "sillas ergonomicas",
    "hoteles baratos",
    "accesorios para mascotas",
    "bicicletas de montaña",
    "suplementos fitness",
    "motos deportivas",
    "teclado mecanico",
    "aplicaciones de recetas",
    "videojuegos de rol",
    "escritorios ajustables",
    "cargador solar portátil",
    "alimento premium gatos",
    "mochilas de senderismo",
    "bicicleta estatica",
    "coches electricos",
    "auriculares gamer",
    "meditacion guiada",
    "peliculas romanticas",
    "macetas decorativas",
    "power bank para viajes",
    "correas para perros",
    "zapatos de senderismo",
    "camisetas running",
    "motos deportivas",
    "reloj Garmin",
    "colchoneta yoga",
    "series policiacas",
    "pantallas LED decorativas",
    "viajes a la playa",
    "accesorios para mascotas",
    "bicicletas de montaña",
    "entrenamiento en casa",
    "motos deportivas",
    "pantalla 4K",
    "recetas veganas",
    "peliculas de ciencia ficcion",
    "luces inteligentes",
    "hoteles baratos",
    "alimento premium gatos",
    "zapatos de senderismo",
    "batidos de proteina",
    "coches electricos",
    "auriculares inalambricos gym",
    "tupper saludables",
    "juegos de estrategia",
    "robots de limpieza"
  ],
  "tema_interes": [
    "mascotas",
    "deportes al aire libre",
    "fitness",
    "movilidad sostenible",
    "videojuegos",
    "salud",
    "entretenimiento",
    "hogar",
    "viajes",
    "mascotas",
    "accesorios de montaña",
    "nutrición",
    "motociclismo",
    "fotografía aérea",
    "crecimiento personal",
    "cine",
    "jardinería",
    "tecnología portátil",
    "mascotas",
    "accesorios de montaña",
    "nutrición deportiva",
    "movilidad sostenible",
    "gaming",
    "alimentación saludable",
    "lectura",
    "oficina saludable",
    "viajes",
    "mascotas",
    "deportes al aire libre",
    "ropa deportiva",
    "motociclismo",
    "wearables",
    "bienestar",
    "cine",
    "decoración",
    "energía renovable",
    "mascotas",
    "accesorios de montaña",
    "ropa deportiva",
    "movilidad sostenible",
    "tecnología",
    "alimentación saludable",
    "entretenimiento",
    "ergonomía",
    "turismo",
    "mascotas",
    "accesorios de montaña",
    "ropa deportiva",
    "motociclismo",
    "gaming",
    "bienestar",
    "videojuegos",
    "hogar",
    "energía renovable",
    "mascotas",
    "deportes al aire libre",
    "otro",
    "movilidad sostenible",
    "cine",
    "salud",
    "cine",
    "hogar inteligente",
    "turismo",
    "mascotas",
    "accesorios de montaña",
    "otro",
    "motociclismo",
    "wearables",
    "bienestar",
    "entretenimiento",
    "hogar inteligente",
    "viajes",
    "mascotas",
    "accesorios de montaña",
    "fitness",
    "movilidad sostenible",
    "tecnología deportiva",
    "salud",
    "cine",
    "hogar inteligente",
    "energía renovable",
    "mascotas",
    "accesorios de montaña",
    "ropa deportiva",
    "motociclismo",
    "cámara de acción",
    "crecimiento personal",
    "entretenimiento",
    "jardinería",
    "tecnología portátil",
    "mascotas",
    "deportes al aire libre",
    "fitness",
    "movilidad sostenible",
    "wearables",
    "salud",
    "entretenimiento",
    "hogar",
    "viajes",
    "mascotas",
    "accesorios de montaña",
    "ropa deportiva",
    "motociclismo",
    "videojuegos",
    "salud",
    "cine",
    "decoración",
    "turismo",
    "mascotas",
    "accesorios de montaña",
    "ropa deportiva",
    "movilidad sostenible",
    "gaming",
    "bienestar",
    "lectura",
    "oficina saludable",
    "viajes",
    "mascotas",
    "deportes al aire libre",
    "nutrición deportiva",
    "motociclismo",
    "tecnología",
    "alimentación saludable",
    "videojuegos",
    "ergonomía",
    "energía renovable",
    "mascotas",
    "accesorios de montaña",
    "fitness",
    "movilidad sostenible",
    "gaming",
    "bienestar",
    "cine",
    "hogar",
    "tecnología portátil",
    "mascotas",
    "accesorios de montaña",
    "otro",
    "motociclismo",
    "wearables",
    "bienestar",
    "entretenimiento",
    "hogar inteligente",
    "turismo",
    "mascotas",
    "deportes al aire libre",
    "otro",
    "motociclismo",
    "cine",
    "alimentación saludable",
    "cine",
    "hogar inteligente",
    "viajes",
    "mascotas",
    "accesorios de montaña",
    "nutrición",
    "movilidad sostenible",
    "tecnología deportiva",
    "salud",
    "entretenimiento",
    "hogar inteligente"
  ],
  "anuncio_sugerido": [
    "Arnés Julius-K9 IDC Power para perros",
    "Bicicleta Trek Marlin 7 con suspensión delantera",
    "Bicicleta Estática Schwinn IC4 con Bluetooth",
    "Tesla Model 3 Long Range AWD 2024",
    "PlayStation 5 Edición Digital",
    "Colección de documentales 'Heal' en Blu-ray",
    "Juego de mesa Catan Edición 25 Aniversario",
    "Set de cuadros minimalistas Nordic para sala",
    "Suscripción Booking.com Genius Level 3",
    "Arnés Julius-K9 IDC Power para perros",
    "Mochila The North Face Terra 55L",
    "Proteína Gold Standard 100% Whey 2.27 kg",
    "Yamaha YZF-R3 ABS 2024",
    "DJI Mini 3 Pro con control remoto RC",
    "Libro 'Los 7 hábitos de la gente altamente efectiva'",
    "Colección Blu-ray John Wick Trilogía",
    "Kit Black+Decker de jardinería 5 piezas",
    "Anker PowerCore 26800mAh con carga rápida",
    "Royal Canin Feline Health Nutrition Indoor",
    "Botas Merrell Moab 3 Mid Waterproof",
    "Creatina Micronizada Optimum Nutrition 300g",
    "Tesla Model 3 Long Range AWD 2024",
    "Logitech G502 HERO RGB 25K",
    "Libro 'Veganomicon' – Cocina vegana gourmet",
    "Libro 'La chica del tren' de Paula Hawkins",
    "Silla ergonómica SIHOO M18 con soporte lumbar",
    "Suscripción Booking.com Genius Level 3",
    "Correa retráctil Flexi Giant 8m",
    "Bicicleta Trek Marlin 7 con suspensión delantera",
    "Nike Air Zoom Pegasus 40",
    "Yamaha YZF-R3 ABS 2024",
    "Garmin Forerunner 255 Music",
    "Kit de Yoga Gaiam Essentials con mat y bloques",
    "Colección Blu-ray Star Wars Saga",
    "Planta Sansevieria en maceta decorativa",
    "Panel solar portátil BigBlue 28W USB",
    "Arnés Julius-K9 IDC Power para perros",
    "Botas Merrell Moab 3 Mid Waterproof",
    "Leggings deportivos Gymshark Adapt",
    "Tesla Model 3 Long Range AWD 2024",
    "Teclado mecánico Razer BlackWidow V4",
    "Suscripción anual a FitMenCook App",
    "Boxset Blu-ray Game of Thrones Completa",
    "Escritorio eléctrico FLEXISPOT EG1",
    "Sombrilla Tommy Bahama con anclaje de arena",
    "Royal Canin Feline Health Nutrition Indoor",
    "Mochila The North Face Terra 55L",
    "Calcetines Nike Everyday Cushion 3 pares",
    "Yamaha YZF-R3 ABS 2024",
    "Auriculares HyperX Cloud II Wireless",
    "Suscripción anual a la app Calm Premium",
    "The Legend of Zelda: Tears of the Kingdom",
    "Set de 3 macetas cerámicas estilo nórdico",
    "Panel solar portátil BigBlue 28W USB",
    "Correa retráctil Flexi Giant 8m",
    "Bicicleta Trek Marlin 7 con suspensión delantera",
    "Producto destacado relacionado con: entrenamiento en casa",
    "Tesla Model 3 Long Range AWD 2024",
    "Samsung Smart TV 55” 4K UHD Crystal",
    "Libro 'Cocina sana para disfrutar' – Isasaweis",
    "Colección Blu-ray 'Antes del amanecer' trilogía",
    "Tira LED Govee RGBIC con control app",
    "Sombrilla Tommy Bahama con anclaje de arena",
    "Royal Canin Feline Health Nutrition Indoor",
    "Botas Merrell Moab 3 Mid Waterproof",
    "Producto destacado relacionado con: camisetas running",
    "Yamaha YZF-R3 ABS 2024",
    "Garmin Fenix 7 Solar",
    "Colchoneta Manduka PRO Yoga Mat 6mm",
    "Boxset Blu-ray Sherlock BBC completa",
    "Philips Hue White & Color Ambiance Kit",
    "Suscripción Booking.com Genius Level 3",
    "Arnés Julius-K9 IDC Power para perros",
    "Mochila The North Face Terra 55L",
    "Mancuernas ajustables Bowflex SelectTech 552",
    "Tesla Model 3 Long Range AWD 2024",
    "Jabra Elite 7 Active True Wireless",
    "Set de Tuppers Rubbermaid Brilliance BPA-Free",
    "Colección Blu-ray Star Wars Saga",
    "iRobot Roomba j7+ con estación de vaciado",
    "Panel solar portátil BigBlue 28W USB",
    "Correa retráctil Flexi Giant 8m",
    "Botas Merrell Moab 3 Mid Waterproof",
    "Camiseta térmica Under Armour ColdGear",
    "Yamaha YZF-R3 ABS 2024",
    "GoPro Hero 12 Black",
    "Libro 'Los 7 hábitos de la gente altamente efectiva'",
    "Juego de mesa Catan Edición 25 Aniversario",
    "Kit Black+Decker de jardinería 5 piezas",
    "Anker PowerCore 26800mAh con carga rápida",
    "Arnés Julius-K9 IDC Power para perros",
    "Bicicleta Trek Marlin 7 con suspensión delantera",
    "Pesa rusa Kettlebell Amazon Basics 12kg",
    "Tesla Model 3 Long Range AWD 2024",
    "Garmin Forerunner 255 Music",
    "Colección de documentales 'Heal' en Blu-ray",
    "Boxset Blu-ray Game of Thrones Completa",
    "Set de cuadros minimalistas Nordic para sala",
    "Suscripción Booking.com Genius Level 3",
    "Royal Canin Feline Health Nutrition Indoor",
    "Mochila The North Face Terra 55L",
    "Nike Air Zoom Pegasus 40",
    "Yamaha YZF-R3 ABS 2024",
    "PlayStation 5 Edición Digital",
    "Libro 'Cocina sana para disfrutar' – Isasaweis",
    "Colección Blu-ray John Wick Trilogía",
    "Planta Sansevieria en maceta decorativa",
    "Sombrilla Tommy Bahama con anclaje de arena",
    "Correa retráctil Flexi Giant 8m",
    "Botas Merrell Moab 3 Mid Waterproof",
    "Leggings deportivos Gymshark Adapt",
    "Tesla Model 3 Long Range AWD 2024",
    "Logitech G502 HERO RGB 25K",
    "Kit de Yoga Gaiam Essentials con mat y bloques",
    "Libro 'La chica del tren' de Paula Hawkins",
    "Silla ergonómica SIHOO M18 con soporte lumbar",
    "Suscripción Booking.com Genius Level 3",
    "Arnés Julius-K9 IDC Power para perros",
    "Bicicleta Trek Marlin 7 con suspensión delantera",
    "Creatina Micronizada Optimum Nutrition 300g",
    "Yamaha YZF-R3 ABS 2024",
    "Teclado mecánico Razer BlackWidow V4",
    "Suscripción anual a FitMenCook App",
    "The Legend of Zelda: Tears of the Kingdom",
    "Escritorio eléctrico FLEXISPOT EG1",
    "Panel solar portátil BigBlue 28W USB",
    "Royal Canin Feline Health Nutrition Indoor",
    "Mochila The North Face Terra 55L",
    "Bicicleta Estática Schwinn IC4 con Bluetooth",
    "Tesla Model 3 Long Range AWD 2024",
    "Auriculares HyperX Cloud II Wireless",
    "Suscripción anual a la app Calm Premium",
    "Colección Blu-ray 'Antes del amanecer' trilogía",
    "Set de 3 macetas cerámicas estilo nórdico",
    "Anker PowerCore 26800mAh con carga rápida",
    "Correa retráctil Flexi Giant 8m",
    "Botas Merrell Moab 3 Mid Waterproof",
    "Producto destacado relacionado con: camisetas running",
    "Yamaha YZF-R3 ABS 2024",
    "Garmin Fenix 7 Solar",
    "Colchoneta Manduka PRO Yoga Mat 6mm",
    "Boxset Blu-ray Sherlock BBC completa",
    "Tira LED Govee RGBIC con control app",
    "Sombrilla Tommy Bahama con anclaje de arena",
    "Arnés Julius-K9 IDC Power para perros",
    "Bicicleta Trek Marlin 7 con suspensión delantera",
    "Producto destacado relacionado con: entrenamiento en casa",
    "Yamaha YZF-R3 ABS 2024",
    "Samsung Smart TV 55” 4K UHD Crystal",
    "Libro 'Veganomicon' – Cocina vegana gourmet",
    "Colección Blu-ray Star Wars Saga",
    "Philips Hue White & Color Ambiance Kit",
    "Suscripción Booking.com Genius Level 3",
    "Royal Canin Feline Health Nutrition Indoor",
    "Botas Merrell Moab 3 Mid Waterproof",
    "Proteína Gold Standard 100% Whey 2.27 kg",
    "Tesla Model 3 Long Range AWD 2024",
    "Jabra Elite 7 Active True Wireless",
    "Set de Tuppers Rubbermaid Brilliance BPA-Free",
    "Juego de mesa Catan Edición 25 Aniversario",
    "iRobot Roomba j7+ con estación de vaciado"
  ]
}

df_busquedas = pd.DataFrame(data)

# --- Función para Sugerir Anuncios ---
def sugerir_anuncios(busqueda_usuario):
    # Convertir la búsqueda del usuario a minúsculas para una comparación insensible a mayúsculas
    busqueda_usuario_lower = busqueda_usuario.lower()

    # Buscar temas de interés relacionados con la búsqueda del usuario
    temas_relacionados = df_busquedas[df_busquedas["busqueda"].str.contains(busqueda_usuario_lower, case=False)]["tema_interes"].unique()

    sugerencias = []
    if len(temas_relacionados) > 0:
        # Si encontramos temas relacionados, sugerimos anuncios basados en esos temas
        for tema in temas_relacionados:
            anuncios_posibles = df_busquedas[df_busquedas["tema_interes"] == tema]["anuncio_sugerido"].tolist()
            sugerencias.extend(anuncios_posibles)
    else:
        # Si no hay coincidencias directas, se podría implementar una lógica más compleja
        # (por ejemplo, buscar palabras clave, usar modelos de embeddings, etc.)
        # Para este ejemplo simple, si no hay coincidencia directa, sugerimos anuncios generales
        sugerencias = ["Anuncios generales: ¡Descubre ofertas en productos variados!", "Prueba nuestros servicios premium", "Explora nuevas categorías"]

    # Eliminar duplicados y devolver una muestra limitada
    return list(set(sugerencias))[:5] # Limitar a 5 sugerencias para no abrumar

# --- Interfaz de Usuario con Streamlit ---
st.set_page_config(page_title="Emulación de Anuncios Sugeridos", layout="centered")

st.title("🔎 Emulación de Sugerencia de Anuncios Basada en Búsquedas")
st.markdown("""
Este ejemplo simula cómo las búsquedas de un usuario en una plataforma
podrían influir en los anuncios que se le muestran.
Introduce algunas palabras clave en el buscador y mira qué anuncios se sugieren.
""")

st.subheader("Simulador de Búsqueda")
user_input = st.text_input("¿Qué estás buscando hoy?", placeholder="Ej: zapatillas deportivas, peliculas de ciencia ficcion, viajes")

if user_input:
    st.subheader("Anuncios Sugeridos para ti:")
    sugerencias_anuncios = sugerir_anuncios(user_input)

    if sugerencias_anuncios:
        for anuncio in sugerencias_anuncios:
            st.info(f"👉 {anuncio}")
    else:
        st.write("No hay sugerencias de anuncios en este momento para tu búsqueda específica. ¡Intenta con otras palabras clave!")

st.markdown("---")
st.subheader("Cómo funciona (Detrás de Escena):")
st.markdown("""
1.  **Conjunto de Datos:** Tenemos un conjunto de datos simple que asocia palabras clave de búsqueda con "temas de interés" (por ejemplo, 'fitness', 'entretenimiento', 'viajes').
2.  **Mapeo:** Cuando ingresas una búsqueda, el sistema intenta mapear tus palabras clave a uno o más de estos temas de interés.
3.  **Sugerencia:** Una vez que se identifica un tema de interés, se muestran anuncios que están pre-asociados con ese tema en nuestro conjunto de datos.
""")

st.subheader("Datos de Ejemplo Utilizados:")
st.dataframe(df_busquedas)

st.caption("Nota: Este es un ejemplo simplificado. Un sistema de sugerencia de anuncios real sería mucho más complejo, utilizando algoritmos de machine learning, análisis de comportamiento del usuario, historial de clics, datos demográficos, etc.")
